server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/mydb  # Nome do serviço no Docker Compose
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rabbitmq  # Nome do serviço no Docker Compose
    port: 5672
    username: guest
    password: guest

consumer:
  queue:
    name: myQueue